repos:
- repo: local
  hooks:
    - id: autoflake
      name: autoflake
      entry: autoflake
      language: python
      types: [python]
      args: [--remove-all-unused-imports, -i]

    - id: isort
      name: isort
      entry: isort
      language: python
      types: [python]
      args: ["--profile", "black", "--filter-files"]

    - id: black
      name: black
      entry: black
      language: python
      types: [python]
